# Generated by Django 5.0.2 on 2024-03-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cor",
            old_name="descricao",
            new_name="nome",
        ),
    ]
